language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

sudo: false

install: mvn install -s support/settings.xml -DskipTests=true -DskipGitVersion=true

script: mvn test -s support/settings.xml -DskipGitVersion=true

notifications:
  irc: "irc.freenode.org#dynjs"
branches:
  except:
    - ir
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
